version: '3.7'
name: eth-ex

services:
  geth:
    container_name: geth
    image: ethereum/client-go
    ports:
      - 8545:8545
      - 30303:30303
      - 8551:8551
      - 5566:5566
    volumes:
      - C:\Users\ali\Desktop\eth:/root
    command:
      - --syncmode=light
      - --ws
      - --ws.port=5566
      - --ws.addr=0.0.0.0
#   front:
#     container_name: ex-front
#     image: ex-front
#     volumes:
#       - ./front:/src/app/front
#       - ex-front-docker-files:/src/app/front/node_modules
#     ports:
#       - 3001:3001
#   back:
#     container_name: ex-back
#     image: ex-back
#     volumes:
#       - ./back:/src/app/back
#       - ex-back-docker-files:/src/app/back/node_modules
#       - ex-back-docker-files:/src/app/back/dist
#     ports:
#       - 3000:3000
# volumes:
#   ex-back-docker-files:
#     external: true
#   ex-front-docker-files:
#     external: true
